global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 0s
  group_interval: 5m
  repeat_interval: 3h
  receiver: node-monitoring
receivers:
  - name: 'node-monitoring'
    webhook_configs:
      - send_resolved: true
        url: 'http://alert-bot:9094'